code cleanup: String to StringBuilder wherever applicable
eclipse-pde/eclipse.pde pull request #1021
Opened 2023-12-20 05:38 UTC by preveen-stack

leverage StringBuilder optimisation cleanup primitives in-built into the eclipse

2023-12-21 23:10 UTC, HannesWell requested changes
Thank you for the contribution.
But not in all cases it makes sense to use a `StringBuilder`.

2023-12-21 23:10 UTC, HannesWell commented on ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetDefinitionManager.java
> +				return name.toString();
```suggestion
				return = name + " [" + id + "]"; //$NON-NLS-1$ //$NON-NLS-2$
```

2023-12-21 23:10 UTC, HannesWell commented on ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetDefinitionManager.java
> +				StringBuilder name = new StringBuilder().append(elem.getAttribute("name")); //$NON-NLS-1$
A StringBuilder is not necessary for static string concatenation. The Java compiler does even smarter things under the hood any ways.
```suggestion
				String name = elem.getAttribute("name"); //$NON-NLS-1$
```

2024-02-11 06:43 UTC, laeubi commented
@preveen-stack can you consider the suggested changes and rebase the branch?

2024-02-11 15:18 UTC, preveen-stack commented
Going through some personal difficulties at the moment. Closing this for now. Will reattempt as soon as possible. The inconvenience caused is deeply regretted. Thanks for understanding.

2024-02-11 15:18 UTC, closed without merging