BndProjectManager: close Processor
eclipse-pde/eclipse.pde pull request #636
Opened 2023-06-23 09:03 UTC by jukzi

Processor is a Closeable that was not closed.

2023-06-23 09:05 UTC, laeubi requested changes
Don't close the processor it is passed to the workspace and managed by this!

2023-06-23 09:07 UTC, jukzi commented
As far as i can see the workspace only calls .getProperty() / getProperties() on it.

2023-06-25 04:53 UTC, laeubi commented on ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/bnd/BndProjectManager.java
> +		try (Processor run = new Processor()) {
can you move the creation of the processor inside the `if (workspace == null) `

2023-07-10 08:13 UTC, laeubi approved these changes
Looks good

2023-07-10 09:40 UTC, jukzi commented
ignoring random fail FeatureBasedLaunchTest https://github.com/eclipse-pde/eclipse.pde/issues/554

2023-07-10 09:40 UTC, merged